Connecting IP Phone to PC, Device, etc.
fusioninventory/fusioninventory-for-glpi pull request #2007
Opened 2016-12-19 10:42 UTC by jsamaniegog

2017-06-30 12:10 UTC, ddurieux requested changes

2017-06-30 12:10 UTC, ddurieux commented on inc/formatconvert.class.php
> +                                                    'MAC'      => 'mac',
Not agree with that, if we are in `CDP`, we don't have the `MAC` field in the XML, see http://fusioninventory.org/documentation/dev/spec/protocol/netinventory.html

2017-07-02 17:56 UTC, jsamaniegog commented on inc/formatconvert.class.php
> +                                                    'MAC'      => 'mac',
That's the problem, when we are in CDP we don't know the mac addresses connected to the port, for this reason i made a pull request in fusioninventory-agent, check this: https://github.com/fusioninventory/fusioninventory-agent/pull/201/files

2018-09-13 05:52 UTC, trasher commented
Is this old PR still actual? Referenced agent PR has not been integrated.

2018-09-13 06:19 UTC, g-bougard commented
A fix included in agent 2.4.1 finally sets SYSMAC in place of MAC for SIP phone while parsing CDP infos (see closed linked agent PR). @jsamaniegog should test it and tell if this answer is still needed or if his trick does a better job.

2024-07-02 08:21 UTC, closed without merging