Fix typo equipment
fusioninventory/fusioninventory-for-glpi pull request #3024
Opened 2020-08-28 13:36 UTC by koshikawa

Fix typo equipment

2020-10-02 08:32 UTC, trasher commented on inc/config.class.php
> +      echo "<td>".__('Network equipment')."</td>";
This string does not seems to exists in core, so:
```suggestion
      echo "<td>".__('Network equipment', 'fusioninventory')."</td>";
```

2020-10-02 08:33 UTC, trasher requested changes
See comment

2020-10-08 11:20 UTC, koshikawa commented
> See comment

OK

2020-10-08 11:44 UTC, trasher approved these changes
Thank you

2020-10-08 12:04 UTC, orthagh approved these changes

2020-10-08 12:16 UTC, merged