Fix unescaped data in SQL query
fusioninventory/fusioninventory-for-glpi pull request #3086
Opened 2021-01-26 12:49 UTC by trasher

2021-01-26 12:49 UTC, trasher commented
ping @flegastelois

2021-01-26 12:55 UTC, orthagh approved these changes

2021-01-26 12:58 UTC, ddurieux requested changes
Need a test, please

2021-07-21 07:01 UTC, cedric-anne approved these changes

2021-10-13 05:54 UTC, closed without merging