feat(core): add force running as massive action
fusioninventory/fusioninventory-for-glpi pull request #3099
Opened 2021-02-24 09:38 UTC by stonebuzz

add 'force running' as massive action

![image](https://user-images.githubusercontent.com/7335054/108980852-6b24b980-768c-11eb-90d7-59e979630242.png)

2021-02-24 10:43 UTC, g-bougard commented on inc/task.class.php
> +                     $ma->addMessage(sprintf(__('Task %1$s is disabled, force runnig aborted',
There a typo there: `runnig` ;-)

2021-02-24 10:49 UTC, cedric-anne commented on inc/task.class.php
> +                     $ma->itemDone($item->getType(), $key, MassiveAction::ACTION_KO);
Not sure it should be considered as an error, maybe using `MassiveAction::NO_ACTION` result would be better.

2021-02-24 11:51 UTC, ddurieux commented
We always refuse to add this feature with in massive action because if you do it on all computers, in case you have really many computers, you can 'ddos' the webserver.

2021-02-24 12:00 UTC, ddurieux requested changes
We always refuse to add this feature with in massive action because if you do it on all computers, in case you have really many computers, you can 'ddos' the webserver.

If you have a mechanism to prevent this, it could be possible to integrated it

2021-02-24 12:49 UTC, stonebuzz commented
maybe queued inventory

https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3066

2021-02-24 13:08 UTC, ddurieux commented
no because it's not only inventory, it's about all requests of agent to server. When you force, there is prolog, inventory and all other tasks (deploy, netinventory, collect...)

2021-02-25 07:40 UTC, stonebuzz commented
Even if all tasks are started, 
they should only run in the defined time slot?

It is the responsibility of the administrator to define the tasks correctly.

Currently the plugin already allows to force the start manually, if the user wants to run them all (one by one) he can also 'ddos' the server.

2021-02-25 07:57 UTC, ddurieux commented
It's not a reason to report the fault to the administrator / technician...
We have the responsibility to guarantee and preserve the server.

It's not a reason someone want a feature we add it. In this case, if hr want it, hr must use tasks or code itself a script (it's his responsibility).

2021-06-14 21:07 UTC, ddurieux commented
I close because not want add this code because introduce problems in the GLPI plugin / server

2021-06-14 21:07 UTC, closed without merging