ADD: add icon on deploy packages
fusioninventory/fusioninventory-for-glpi pull request #3233
Opened 2021-10-01 07:10 UTC by aperret-dcs

2021-10-26 07:27 UTC, ddurieux requested changes

2021-10-26 07:27 UTC, ddurieux commented on install/mysql/plugin_fusioninventory-empty.sql
> +  `style` varchar(10) DEFAULT NULL,
These 2 new columns must have be managed in `update.php` page to be created when update the plugin

2021-10-26 07:27 UTC, ddurieux commented on inc/deploypackage.class.php
> +      echo __('Icône actuelle', 'fusioninventory') . ' : ';
In english please

2021-10-26 07:27 UTC, ddurieux commented on inc/deploypackage.class.php
> +      echo __('Choisir une icône pour ce service de la boutique', 'fusioninventory') . ' :';
In english too

2021-10-26 09:32 UTC, aperret-dcs commented on install/mysql/plugin_fusioninventory-empty.sql
> +  `style` varchar(10) DEFAULT NULL,
Modification faite dans le fichier install/update.php

2021-10-29 08:57 UTC, ddurieux approved these changes

2021-10-29 08:57 UTC, merged